server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://${db-server}:5432/userservice
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:    hibernate:      ddl-auto: update
    show-sql: true
    properties:      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true  application:    name: user-service   

logPath: ${logPath}
springAppName: user-service